version: '3'
services:
  postgres:
    image: "postgres:14.3-alpine"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
#      - "./internal/pkg/postgres/migrations:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=graphql
      - POSTGRES_USER=graphql_api
      - POSTGRES_PASSWORD=_please_change_me_now_
volumes:
  db:
