version: '3'
services:
  postgres:
    image: "postgres:13.0"
    ports:
      - "5432:5432"
    volumes:
      - "./.data/docker-data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=graphql
      - POSTGRES_USER=graphql_api
      - POSTGRES_PASSWORD=_please_change_me_now_